#!/usr/bin/env bash

source "$HOME/.config/sketchybar/variables.sh" # Loads all defined colors

# General bar and defaults
default=(
    icon.font="$FONT:Bold:13.5"
	icon.color="$ICON_COLOR"
	icon.padding_left=0
	icon.padding_right=0
	label.font="$FONT:Bold:13.0"
	label.color="$LABEL_COLOR"
	label.padding_left=0
	label.padding_right=0
	label.background.height=$HEIGHT
	background.padding_right=0
	background.padding_left=0
	updates=when_shown
)

bar=(
    height=$HEIGHT
    color="$BAR_COLOR"
	shadow="$SHADOW"
	position=bottom
	sticky=on
	padding_right=10
	padding_left=50
	y_offset=0
	margin=0
	blur_radius=20
	notch_width=200
	font_smoothing=on
	topmost=true
	sticky=true
)

sketchybar --default "${default[@]}" --bar "${bar[@]}"

source "items.sh"


#################### Finalizing Setup ####################

sketchybar --hotload true
sketchybar --update

echo "sketchybar configuration loaded.."
