#!/usr/bin/env bash

source "$HOME/.config/sketchybar/variables.sh" # Loads all defined colors

# General bar and defaults
default=(
    icon.font="$FONT:$FONT_WEIGHT:$FONT_SIZE"
	icon.color="$ICON_COLOR"
	icon.padding_left=0
	icon.padding_right=0
	label.font="$FONT:$FONT_WEIGHT:$FONT_SIZE"
	label.color="$LABEL_COLOR"
	label.padding_left=0
	label.padding_right=0
	label.background.height=$HEIGHT
	background.padding_right=0
	background.padding_left=0
	updates=when_shown
)

bar=(
    height=$HEIGHT
    color="$BAR_COLOR"
	position=top
	padding_right=$BAR_PADDING_RIGHT
	padding_left=$BAR_PADDING_LEFT
	margin=0
	blur_radius=$BAR_BLUR_RADIUS
	notch_width=$BAR_NOTCH_WIDTH
	font_smoothing=on
	topmost=false
	sticky=true
)

sketchybar --default "${default[@]}" --bar "${bar[@]}"

sketchybar --add event paneru_manage_change

source "items.sh"


#################### Finalizing Setup ####################

sketchybar --hotload true
sketchybar --update

echo "sketchybar configuration loaded.."
