remote_theme: mmistakes/minimal-mistakes@4.28.0
plugins:
- jekyll-remote-theme
- jekyll-include-cache

title: My personal dotfiles
description: Rendered dotfiles for macOS. Source managed with chezmoi on the main branch.

atom_feed:
  hide: true

name: Ronald Suwandi
