[tools]
go = "latest"
java = "temurin"
node = "latest"
python = "latest"
bun = "latest"
rust = "latest"

# bootstrap sections
[bootstrap.macos.dock]
autohide = false
orientation = "left"
tilesize = 32
magnification = true
largesize = 46
show_recents = false
mru_spaces = false


[bootstrap.macos.finder]
show_pathbar = true
show_status_bar = true
preferred_view_style = "list"

[bootstrap.macos.trackpad]
tap_to_click = true

[bootstrap.macos.defaults]
"com.apple.spaces" = { 
    "app-bindings" = {
        "com.1password.1password" = "AllSpaces",
        "com.apple.activitymonitor" = "AllSpaces",
        "info.filesmanager.files" = "AllSpaces",
	}
}
"com.apple.AppleMultitouchTrackpad" = {
    TrackpadCornerSecondaryClick = 0,
    TrackpadFiveFingerPinchGesture = 2,
    TrackpadFourFingerHorizSwipeGesture = 2,
    TrackpadFourFingerPinchGesture = 2,
    TrackpadFourFingerVertSwipeGesture = 2,
    TrackpadThreeFingerDrag = true,
    TrackpadThreeFingerHorizSwipeGesture = 0,
    TrackpadThreeFingerTapGesture = 0,
    TrackpadThreeFingerVertSwipeGesture = 0,
    TrackpadTwoFingerDoubleTapGesture = 1,
    TrackpadTwoFingerFromRightEdgeSwipeGesture = 0,
}
